name: mini_web_app_manager_stacked
description: A Flutter project using Stacked architecture
publish_to: "none" # prevent accidental publishing

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  stacked: ^3.4.2
  stacked_services: ^1.1.1
  shared_preferences: ^2.3.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  stacked_generator: ^1.5.1
